const BASE="https://dps.psx.com.pk";
const timeoutMs=Number(process.env.PSX_TIMEOUT_MS||15000);
function headers(){return {"User-Agent":process.env.PSX_MCP_USER_AGENT||"PSX-MCP-Gateway/1.0", "X-Requested-With":"XMLHttpRequest",Accept:"application/json,text/plain,*/*"};}
async function psxFetch(path:string,init:RequestInit={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${BASE}${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:"no-store",signal:c.signal});const text=await r.text();if(!r.ok)throw new Error(`PSX HTTP ${r.status}: ${text.slice(0,300)}`);return text;}finally{clearTimeout(t)}}
function n(v:any){if(v===null||v===undefined||v==="")return null;const x=Number(String(v).replace(/,/g,"").replace(/%/g,""));return Number.isFinite(x)?x:null}
function rows(p:any):any[]{if(Array.isArray(p))return p;for(const k of ["data","rows","result","results","companies","records"])if(Array.isArray(p?.[k]))return p[k];return []}
function norm(r:any){if(Array.isArray(r))return {symbol:r[0],sector:r[1],listedIn:r[2],ldcp:n(r[3]),open:n(r[4]),high:n(r[5]),low:n(r[6]),current:n(r[7]),change:n(r[8]),changePct:n(r[9]),volume:n(r[10])};return {symbol:r.SYMBOL??r.symbol,name:r.NAME??r.name??r["COMPANY NAME"],sector:r.SECTOR??r.sector??r.sectorName,listedIn:r["LISTED IN"]??r.LISTED_IN??r.listedIn,ldcp:n(r.LDCP??r.ldcp),open:n(r.OPEN??r.open),high:n(r.HIGH??r.high),low:n(r.LOW??r.low),current:n(r.CURRENT??r.current??r.price),change:n(r.CHANGE??r.change),changePct:n(r["CHANGE (%)"]??r.CHANGE_PCT??r.changePct),volume:n(r.VOLUME??r.volume)};}
export async function marketWatch(){const text=await psxFetch("/market-watch");let p:any;try{p=JSON.parse(text)}catch{throw new Error("PSX /market-watch did not return JSON; portal format may have changed.")};const data=rows(p).map(norm).filter((r:any)=>r.symbol);return {source:BASE+"/market-watch",fetchedAt:new Date().toISOString(),count:data.length,data}}
export async function symbols(){const text=await psxFetch("/symbols");let p:any;try{p=JSON.parse(text)}catch{throw new Error("PSX /symbols did not return JSON.")};return {source:BASE+"/symbols",fetchedAt:new Date().toISOString(),count:rows(p).length,data:rows(p)}}
export async function quote(symbol:string){const s=symbol.trim().toUpperCase();const m=await marketWatch();const r=m.data.find((x:any)=>String(x.symbol).toUpperCase()===s);if(!r)throw new Error(`Symbol ${s} was not found.`);return {...r,source:m.source,fetchedAt:m.fetchedAt}}
export async function eod(symbol:string){const s=symbol.trim().toUpperCase();const text=await psxFetch(`/timeseries/eod/${encodeURIComponent(s)}`);let p:any;try{p=JSON.parse(text)}catch{throw new Error(`PSX EOD endpoint for ${s} did not return JSON.`)};return {symbol:s,source:`${BASE}/timeseries/eod/${s}`,fetchedAt:new Date().toISOString(),data:rows(p).map((r:any)=>Array.isArray(r)?{timestamp:r[0],close:n(r[1]),volume:n(r[2]),open:n(r[3]),high:n(r[4]),low:n(r[5])}:r)}}
export async function intraday(symbol:string){const s=symbol.trim().toUpperCase();const text=await psxFetch(`/timeseries/int/${encodeURIComponent(s)}`);let p:any;try{p=JSON.parse(text)}catch{throw new Error(`PSX intraday endpoint for ${s} did not return JSON.`)};return {symbol:s,source:`${BASE}/timeseries/int/${s}`,fetchedAt:new Date().toISOString(),data:rows(p)}}
async function postData(path:string,symbol:string|undefined,limit:number){const b=new URLSearchParams();b.set("type","C");b.set("page","1");if(symbol)b.set("symbol",symbol.trim().toUpperCase());const text=await psxFetch(path,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b});try{const p=JSON.parse(text);return {source:BASE+path,fetchedAt:new Date().toISOString(),data:rows(p).slice(0,Math.max(1,Math.min(limit,50)))}}catch{return {source:BASE+path,fetchedAt:new Date().toISOString(),warning:"Endpoint returned non-JSON",rawPreview:text.slice(0,1000)}}}
export async function announcements(symbol?:string,limit=10){return postData("/announcements",symbol,limit)}
export async function payouts(symbol?:string,limit=10){const b=new URLSearchParams();b.set("page","1");if(symbol)b.set("symbol",symbol.trim().toUpperCase());const text=await psxFetch("/payouts",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b});try{const p=JSON.parse(text);return {source:BASE+"/payouts",fetchedAt:new Date().toISOString(),data:rows(p).slice(0,Math.max(1,Math.min(limit,50)))}}catch{return {source:BASE+"/payouts",fetchedAt:new Date().toISOString(),warning:"Endpoint returned non-JSON",rawPreview:text.slice(0,1000)}}}
export async function marketSnapshot(limit=10){const m=await marketWatch();const v=m.data.filter((r:any)=>typeof r.changePct==="number");const gain=[...v].sort((a:any,b:any)=>(b.changePct??-999)-(a.changePct??-999)).slice(0,limit);const lose=[...v].sort((a:any,b:any)=>(a.changePct??999)-(b.changePct??999)).slice(0,limit);const vol=[...m.data].sort((a:any,b:any)=>(b.volume??-1)-(a.volume??-1)).slice(0,limit);return {fetchedAt:m.fetchedAt,universeCount:m.count,breadth:{advancers:v.filter((r:any)=>(r.changePct??0)>0).length,decliners:v.filter((r:any)=>(r.changePct??0)<0).length,unchanged:v.filter((r:any)=>(r.changePct??0)===0).length},topGainers:gain,topLosers:lose,topVolume:vol,source:m.source}}
